//! Lightweight, always-runnable conformance check (no Docker/boto3 needed).
//!
//! The full Ceph `s3-tests` suite is run by `scripts/run-s3tests.sh` in CI (where Docker is
//! available). This in-repo test exercises the SAME S3-shaped behaviors over real HTTP, but
//! without external tooling, so it runs in any dev environment. It validates the parts `s3s`
//! can NOT cover for us: our HDFS-specific translation choices (directory handling, ETag
//! semantics, listing pagination, write-op policy) as seen by a real HTTP S3 client.

use std::collections::HashSet;
use std::time::Duration;

use hdfs_native::minidfs::MiniDfs;
use hdfs_native::{Client, ClientBuilder, WriteOptions};
use hdfs_s3_gateway::config::Config;
use hdfs_s3_gateway::s3::server::{build_service, serve};
use hdfs_s3_gateway::s3::HdfsGateway;
use reqwest::Client as HttpClient;

use bytes::Bytes;

async fn start_gateway(
    dfs: &MiniDfs,
) -> (
    std::net::SocketAddr,
    tokio::task::JoinHandle<std::io::Result<()>>,
) {
    let config = Config {
        namenode_uri: dfs.url.clone(),
        hdfs_root: "/".to_string(),
        bucket_name: "hdfs".to_string(),
        listen_addr: "127.0.0.1:0".to_string(),
        max_concurrent_requests: 2048,
        expose_upstream_errors: false,
        hdfs_options: Default::default(),
        hdfs_config_dir: None,
        hdfs_user: None,
    };
    let client = ClientBuilder::new().with_url(&dfs.url).build().unwrap();
    let gateway = HdfsGateway::new(client, config.clone());
    let service = build_service(gateway, &config);
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let addr = listener.local_addr().unwrap();
    let handle = tokio::spawn(serve(listener, service, std::future::pending()));
    (addr, handle)
}

async fn write_file(client: &Client, path: &str, data: &[u8]) {
    let mut writer = client
        .create(path, &WriteOptions::default().overwrite(true))
        .await
        .unwrap();
    writer
        .write_bytes(Bytes::copy_from_slice(data))
        .await
        .unwrap();
    writer.close().await.unwrap();
}

#[tokio::test]
async fn conformance_http() {
    let _ = env_logger::builder().is_test(true).try_init();
    let dfs = MiniDfs::with_features(&HashSet::new());
    let hdfs = ClientBuilder::new().with_url(&dfs.url).build().unwrap();

    // Fixtures: a file, a directory (must NOT be an object), and a nested tree.
    write_file(&hdfs, "/data/obj.txt", b"conformance-body").await;
    write_file(&hdfs, "/data/dir/nested.txt", b"nested").await;

    let (addr, _handle) = start_gateway(&dfs).await;
    let base = format!("http://{addr}/hdfs");
    let http = HttpClient::builder()
        .timeout(Duration::from_secs(10))
        .build()
        .unwrap();

    // --- HEAD returns 200 with Content-Length, ETag, and a request id -------------------
    // The `x-amz-request-id` is generated by the gateway (we are not AWS) and attached via
    // the supported `S3Response.headers` field, which s3s appends without clobbering others.
    let resp = http
        .head(format!("{base}/data/obj.txt"))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 200);
    assert_eq!(resp.headers().get("content-length").unwrap(), "16");
    assert!(resp.headers().get("etag").is_some(), "ETag must be present");
    assert!(
        resp.headers().get("x-amz-request-id").is_some(),
        "request-id must be present"
    );

    // --- GET full body matches exactly ---------------------------------------------------
    let resp = http
        .get(format!("{base}/data/obj.txt"))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 200);
    let body = resp.bytes().await.unwrap();
    assert_eq!(&body[..], b"conformance-body");

    // --- GET range via real HTTP (bytes=0-4) ---------------------------------------------
    let resp = http
        .get(format!("{base}/data/obj.txt"))
        .header("range", "bytes=0-4")
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 206, "partial content for satisfiable range");
    assert_eq!(resp.headers().get("content-range").unwrap(), "bytes 0-4/16");
    let body = resp.bytes().await.unwrap();
    assert_eq!(&body[..], b"confo", "bytes=0-4 is inclusive → 5 bytes");

    // --- GET on a directory → 404 NoSuchKey ----------------------------------------
    let resp = http.get(format!("{base}/data/dir")).send().await.unwrap();
    assert_eq!(resp.status(), 404);

    // --- GET on a missing key → 404 ------------------------------------------------------
    let resp = http
        .get(format!("{base}/data/missing.txt"))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 404);

    // --- LIST (no delimiter) returns both files as Contents ------------------------------
    let resp = http
        .get(format!("{base}/?list-type=2"))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 200);
    let xml = resp.text().await.unwrap();
    assert!(
        xml.contains("<Key>data/obj.txt</Key>"),
        "listing must include obj.txt: {xml}"
    );
    assert!(
        xml.contains("<Key>data/dir/nested.txt</Key>"),
        "listing must include nested.txt: {xml}"
    );

    // --- LIST with delimiter collapses the directory to a CommonPrefix ------------------
    let resp = http
        .get(format!("{base}/?list-type=2&delimiter=/"))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 200);
    let xml = resp.text().await.unwrap();
    assert!(
        xml.contains("<Prefix>data/</Prefix>"),
        "directory must collapse to CommonPrefix: {xml}"
    );

    // --- WRITE op over HTTP → 403 AccessDenied (read-only policy) ---------------
    let resp = http
        .put(format!("{base}/data/new.txt"))
        .body("x")
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 403, "PUT must be denied");
    let xml = resp.text().await.unwrap();
    assert!(
        xml.contains("AccessDenied"),
        "denial must be AccessDenied: {xml}"
    );

    // --- bucket-config probe returns 200 with empty shape ----------------------
    let resp = http
        .get(format!("{base}/?versioning"))
        .send()
        .await
        .unwrap();
    assert_eq!(resp.status(), 200);
}
