from typing import Optional

class GatewayError(Exception): ...

class Gateway:
    def __init__(
        self,
        config_path: Optional[str] = None,
        *,
        namenode_uri: Optional[str] = None,
        hdfs_root: Optional[str] = None,
        bucket_name: Optional[str] = None,
        listen_addr: Optional[str] = None,
    ) -> None: ...
    @property
    def listen_addr(self) -> str: ...
    @property
    def address(self) -> Optional[str]: ...
    @property
    def is_running(self) -> bool: ...
    def serve_blocking(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
